### ISSUE TITLE
Django 1.9 importError: cannot import name 'Constraint' - issue still open

### ISSUE THREAD

**Issue by Tomatosoup97** [deschler/django-modeltranslation#355]
Using django 1.9 and latest modeltranslation version, i still get this import error when i try to makemigrations / runserver / migrate

```python
(venv)mat@linuxmint ~/Desktop/python/pmm $ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mat/Desktop/python/pmm/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/mat/Desktop/python/pmm/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/home/mat/Desktop/python/pmm/venv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mat/Desktop/python/pmm/venv/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/mat/Desktop/python/pmm/venv/lib/python3.4/site-packages/modeltranslation/apps.py", line 11, in ready
    handle_translation_registrations()
  File "/home/mat/Desktop/python/pmm/venv/lib/python3.4/site-packages/modeltranslation/models.py", line 81, in handle_translation_registrations
    autodiscover()
  File "/home/mat/Desktop/python/pmm/venv/lib/python3.4/site-packages/modeltranslation/models.py", line 16, in autodiscover
    from modeltranslation.translator import translator
  File "/home/mat/Desktop/python/pmm/venv/lib/python3.4/site-packages/modeltranslation/translator.py", line 12, in <module>
    from modeltranslation.manager import (MultilingualManager, MultilingualQuerysetManager,
  File "/home/mat/Desktop/python/pmm/venv/lib/python3.4/site-packages/modeltranslation/manager.py", line 19, in <module>
    from django.db.models.sql.where import Constraint
ImportError: cannot import name 'Constraint'
```

**Comment by PythonicNinja** [comment]
:+1 for fixing the problem

**Comment by zlorf** [comment]
Are you sure you're using the latest version (`0.11rc2`)?

**Comment by Tomatosoup97** [comment]
Yes, i was sure, and the error was still showing. Dunno if you have made any changes since i had reported this issue(20 days ago)

**Comment by zlorf** [comment]
No, I haven't made any changes, yet the error is puzzling, as https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/manager.py#L19 is not the line shown in the stacktrace, and moreover code there is wrapper in `try - except ImportError`, so this shouldn't happen.

**Comment by jonashagstedt** [comment]
I tried `pip install django-modeltranslation==0.11rc2` and I don't get this error anymore (if that is helpful)

**Comment by bartmika** [comment]
+1

**Comment by bartmika** [comment]
@jonashagstedt thanks! Your suggestion fixed the problem. :+1: 

Question, when will the latest code be available on PyPi though?

**Comment by zlorf** [comment]
Gosh, IT IS available on PyPi. Where do you think `pip install django-modeltranslation==0.11rc2` is getting code from?
If you're asking when the latest code it will be marked as STABLE - I'm waiting for @Tomatosoup97 to confirm that his issue is resolved with `0.11rc2`.

**Comment by Tomatosoup97** [comment]
@zlorf i cant confirm that this issue is resolved, because of the deadline i couldnt wait so long and i changed package used for model translation. 

@jonashagstedt and @bartmika said that `0.11rc2` solved the problem so lets mark this issue as closed

**Comment by zlorf** [comment]
Ok! @deschler , I think we can make 0.11 release when you have time.

**Comment by deschler** [comment]
Released rc2 without changes.

**Comment by jestinmwilson** [comment]
ImportError: cannot import name 'UniqueConstraint' from 'django.db.models'

i tried this one "pip install django-modeltranslation==0.11rc2" but
still getting the same error

**Comment by Tomatosoup97** [comment]
@jestinmwilson 0.11rc2 is an old version that I belive you don't want to use. If there is an error in the latest one then I'd advise creating a new issues; this one is unrelated.
